# Generated by Django 4.2.1 on 2023-05-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_player_team_championship'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/player_images'),
        ),
    ]
