# Generated by Django 4.2.1 on 2023-05-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_player_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='team_images/'),
        ),
    ]
