# Generated by Django 4.2.1 on 2023-05-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_player_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championship',
            name='teams',
            field=models.ManyToManyField(related_name='championships', to='main.team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='birth_date',
            field=models.DateTimeField(),
        ),
    ]
