# Generated by Django 4.2.1 on 2023-05-14 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_match_tabellino'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('championship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendario', to='main.championship')),
            ],
            options={
                'verbose_name_plural': 'Calendari',
            },
        ),
        migrations.CreateModel(
            name='Giornata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giornate', to='main.calendario')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='giornata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partite', to='main.giornata'),
        ),
    ]
