# Generated by Django 4.2.1 on 2023-05-14 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_match_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='championship',
        ),
    ]
