# Generated by Django 4.2.1 on 2023-05-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_match_championship'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='blocks',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stat',
            name='rebounds',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
