# Generated by Django 4.2.1 on 2023-05-15 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_stat_blocks_stat_rebounds_alter_stat_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabellino',
            name='statA10',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statA10', to='main.stat'),
        ),
        migrations.AlterField(
            model_name='tabellino',
            name='statA11',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statA11', to='main.stat'),
        ),
        migrations.AlterField(
            model_name='tabellino',
            name='statA12',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statA12', to='main.stat'),
        ),
        migrations.AlterField(
            model_name='tabellino',
            name='statA2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statA2', to='main.stat'),
        ),
        migrations.AlterField(
            model_name='tabellino',
            name='statA3',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statA3', to='main.stat'),
        ),
        migrations.AlterField(
            model_name='tabellino',
            name='statA4',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statA4', to='main.stat'),
        ),
        migrations.AlterField(
            model_name='tabellino',
            name='statA5',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statA5', to='main.stat'),
        ),
        migrations.AlterField(
            model_name='tabellino',
            name='statA6',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statA6', to='main.stat'),
        ),
        migrations.AlterField(
            model_name='tabellino',
            name='statA7',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statA7', to='main.stat'),
        ),
        migrations.AlterField(
            model_name='tabellino',
            name='statA8',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statA8', to='main.stat'),
        ),
        migrations.AlterField(
            model_name='tabellino',
            name='statA9',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statA9', to='main.stat'),
        ),
        migrations.AlterField(
            model_name='tabellino',
            name='statB10',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statB10', to='main.stat'),
        ),
        migrations.AlterField(
            model_name='tabellino',
            name='statB11',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statB11', to='main.stat'),
        ),
        migrations.AlterField(
            model_name='tabellino',
            name='statB12',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statB12', to='main.stat'),
        ),
        migrations.AlterField(
            model_name='tabellino',
            name='statB2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statB2', to='main.stat'),
        ),
        migrations.AlterField(
            model_name='tabellino',
            name='statB3',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statB3', to='main.stat'),
        ),
        migrations.AlterField(
            model_name='tabellino',
            name='statB4',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statB4', to='main.stat'),
        ),
        migrations.AlterField(
            model_name='tabellino',
            name='statB5',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statB5', to='main.stat'),
        ),
        migrations.AlterField(
            model_name='tabellino',
            name='statB6',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statB6', to='main.stat'),
        ),
        migrations.AlterField(
            model_name='tabellino',
            name='statB7',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statB7', to='main.stat'),
        ),
        migrations.AlterField(
            model_name='tabellino',
            name='statB8',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statB8', to='main.stat'),
        ),
        migrations.AlterField(
            model_name='tabellino',
            name='statB9',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statB9', to='main.stat'),
        ),
    ]
