# Generated by Django 4.2.1 on 2023-05-15 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_tabellino_stata10_alter_tabellino_stata11_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='championship',
            name='teams',
        ),
        migrations.AddField(
            model_name='team',
            name='championships',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='main.championship'),
        ),
        migrations.AlterField(
            model_name='match',
            name='tabellino',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partita', to='main.tabellino'),
        ),
    ]
