# Generated by Django 4.2.1 on 2023-05-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_championship_teams_team_championships_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
