# Generated by Django 4.2.1 on 2023-05-17 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_stat_valid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giornata',
            options={'verbose_name_plural': 'Giornate'},
        ),
        migrations.AlterModelOptions(
            name='tabellino',
            options={'verbose_name_plural': 'Tabellini'},
        ),
        migrations.RemoveField(
            model_name='match',
            name='tabellino',
        ),
        migrations.RemoveField(
            model_name='tabellino',
            name='statA1',
        ),
        migrations.RemoveField(
            model_name='tabellino',
            name='statA10',
        ),
        migrations.RemoveField(
            model_name='tabellino',
            name='statA11',
        ),
        migrations.RemoveField(
            model_name='tabellino',
            name='statA12',
        ),
        migrations.RemoveField(
            model_name='tabellino',
            name='statA2',
        ),
        migrations.RemoveField(
            model_name='tabellino',
            name='statA3',
        ),
        migrations.RemoveField(
            model_name='tabellino',
            name='statA4',
        ),
        migrations.RemoveField(
            model_name='tabellino',
            name='statA5',
        ),
        migrations.RemoveField(
            model_name='tabellino',
            name='statA6',
        ),
        migrations.RemoveField(
            model_name='tabellino',
            name='statA7',
        ),
        migrations.RemoveField(
            model_name='tabellino',
            name='statA8',
        ),
        migrations.RemoveField(
            model_name='tabellino',
            name='statA9',
        ),
        migrations.RemoveField(
            model_name='tabellino',
            name='statB1',
        ),
        migrations.RemoveField(
            model_name='tabellino',
            name='statB10',
        ),
        migrations.RemoveField(
            model_name='tabellino',
            name='statB11',
        ),
        migrations.RemoveField(
            model_name='tabellino',
            name='statB12',
        ),
        migrations.RemoveField(
            model_name='tabellino',
            name='statB2',
        ),
        migrations.RemoveField(
            model_name='tabellino',
            name='statB3',
        ),
        migrations.RemoveField(
            model_name='tabellino',
            name='statB4',
        ),
        migrations.RemoveField(
            model_name='tabellino',
            name='statB5',
        ),
        migrations.RemoveField(
            model_name='tabellino',
            name='statB6',
        ),
        migrations.RemoveField(
            model_name='tabellino',
            name='statB7',
        ),
        migrations.RemoveField(
            model_name='tabellino',
            name='statB8',
        ),
        migrations.RemoveField(
            model_name='tabellino',
            name='statB9',
        ),
        migrations.AddField(
            model_name='match',
            name='tabellinoA',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partitaA', to='main.tabellino'),
        ),
        migrations.AddField(
            model_name='match',
            name='tabellinoB',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partitaB', to='main.tabellino'),
        ),
        migrations.AddField(
            model_name='tabellino',
            name='stat1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stat1', to='main.stat'),
        ),
        migrations.AddField(
            model_name='tabellino',
            name='stat10',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stat10', to='main.stat'),
        ),
        migrations.AddField(
            model_name='tabellino',
            name='stat11',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stat11', to='main.stat'),
        ),
        migrations.AddField(
            model_name='tabellino',
            name='stat12',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stat12', to='main.stat'),
        ),
        migrations.AddField(
            model_name='tabellino',
            name='stat2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stat2', to='main.stat'),
        ),
        migrations.AddField(
            model_name='tabellino',
            name='stat3',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stat3', to='main.stat'),
        ),
        migrations.AddField(
            model_name='tabellino',
            name='stat4',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stat4', to='main.stat'),
        ),
        migrations.AddField(
            model_name='tabellino',
            name='stat5',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stat5', to='main.stat'),
        ),
        migrations.AddField(
            model_name='tabellino',
            name='stat6',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stat6', to='main.stat'),
        ),
        migrations.AddField(
            model_name='tabellino',
            name='stat7',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stat7', to='main.stat'),
        ),
        migrations.AddField(
            model_name='tabellino',
            name='stat8',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stat8', to='main.stat'),
        ),
        migrations.AddField(
            model_name='tabellino',
            name='stat9',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stat9', to='main.stat'),
        ),
    ]
