# Generated by Django 4.2.1 on 2023-05-19 08:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_giornata_options_alter_tabellino_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendario',
            name='classifica',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, null=True, size=None),
        ),
    ]
