# Generated by Django 4.2.1 on 2023-05-19 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_calendario_classifica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendario',
            name='classifica',
        ),
    ]
