# Generated by Django 4.2.1 on 2023-05-21 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_match_tabellinoa_alter_match_tabellinob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('birth_date', models.DateTimeField()),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='staff_images/')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coaches', to='main.team')),
            ],
        ),
    ]
