# Generated by Django 4.2.1 on 2023-05-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='pointsA',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='pointsB',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
