# Generated by Django 4.2.1 on 2023-05-22 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_match_pointsa_alter_match_pointsb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giornata',
            options={'ordering': ['num'], 'verbose_name_plural': 'Giornate'},
        ),
    ]
