# Generated by Django 4.2.1 on 2023-05-22 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_giornata_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['last_name', 'name']},
        ),
    ]
