# Generated by Django 4.2.1 on 2023-05-22 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_player_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name']},
        ),
    ]
