# Generated by Django 4.2.1 on 2023-05-24 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_commento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commento',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenti', to='main.match'),
        ),
    ]
