# Generated by Django 4.2.1 on 2023-05-27 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_commento_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='championship',
            options={'ordering': ['name', 'year']},
        ),
    ]
