# Generated by Django 4.2.1 on 2023-05-27 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_like_dislike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['date']},
        ),
    ]
