# Generated by Django 4.2.1 on 2023-06-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_championship_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='birth_date',
            field=models.DateField(default='01/01/2001'),
        ),
        migrations.AlterField(
            model_name='player',
            name='birth_date',
            field=models.DateField(default='01/01/2001'),
        ),
    ]
